// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using film_app_magisterka.DAL;

#nullable disable

namespace film_app_magisterka.Migrations
{
    [DbContext(typeof(FilmsContext))]
    partial class FilmsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("film_app_magisterka.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Desc = "Filmy pełne dynamicznych scen i efektów specjalnych.",
                            Name = "Akcja"
                        },
                        new
                        {
                            CategoryId = 2,
                            Desc = "Filmy dostarczające dużą dawkę humoru i rozrywki.",
                            Name = "Komedia"
                        },
                        new
                        {
                            CategoryId = 3,
                            Desc = "Filmy o poważnej tematyce, często poruszające trudne tematy.",
                            Name = "Dramat"
                        },
                        new
                        {
                            CategoryId = 4,
                            Desc = "Filmy mające na celu wywołanie strachu i napięcia.",
                            Name = "Horror"
                        },
                        new
                        {
                            CategoryId = 5,
                            Desc = "Filmy opowiadające o przyszłości, technologii i kosmosie.",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            CategoryId = 6,
                            Desc = "Filmy osadzone w magicznych światach, pełne nadprzyrodzonych zjawisk.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 7,
                            Desc = "Filmy pełne napięcia, zagadek i zwrotów akcji.",
                            Name = "Thriller"
                        },
                        new
                        {
                            CategoryId = 8,
                            Desc = "Filmy animowane, często skierowane do dzieci i rodzin.",
                            Name = "Animacja"
                        },
                        new
                        {
                            CategoryId = 9,
                            Desc = "Filmy przedstawiające prawdziwe wydarzenia i historie.",
                            Name = "Dokument"
                        },
                        new
                        {
                            CategoryId = 10,
                            Desc = "Filmy, w których ważnym elementem są piosenki i taniec.",
                            Name = "Musical"
                        });
                });

            modelBuilder.Entity("film_app_magisterka.Models.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            CategoryId = 1,
                            Description = "Postapokaliptyczna walka o przetrwanie.",
                            Director = "George Miller",
                            Price = 29.99m,
                            Title = "Mad Max: Na drodze gniewu"
                        },
                        new
                        {
                            FilmId = 2,
                            CategoryId = 2,
                            Description = "Niepoprawny komediowy antybohater.",
                            Director = "Tim Miller",
                            Price = 24.99m,
                            Title = "Deadpool"
                        },
                        new
                        {
                            FilmId = 3,
                            CategoryId = 3,
                            Description = "Historia niezwykłego człowieka o wielkim sercu.",
                            Director = "Robert Zemeckis",
                            Price = 19.99m,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            FilmId = 4,
                            CategoryId = 4,
                            Description = "Przerażająca historia hotelu i jego mieszkańców.",
                            Director = "Stanley Kubrick",
                            Price = 22.99m,
                            Title = "Lśnienie"
                        },
                        new
                        {
                            FilmId = 5,
                            CategoryId = 5,
                            Description = "Podróż w nieznane w poszukiwaniu nowego domu.",
                            Director = "Christopher Nolan",
                            Price = 34.99m,
                            Title = "Interstellar"
                        },
                        new
                        {
                            FilmId = 6,
                            CategoryId = 6,
                            Description = "Początek epickiej przygody w Śródziemiu.",
                            Director = "Peter Jackson",
                            Price = 39.99m,
                            Title = "Władca Pierścieni: Drużyna Pierścienia"
                        },
                        new
                        {
                            FilmId = 7,
                            CategoryId = 7,
                            Description = "Mroczny thriller pełen zwrotów akcji.",
                            Director = "David Fincher",
                            Price = 26.99m,
                            Title = "Zaginiona dziewczyna"
                        },
                        new
                        {
                            FilmId = 8,
                            CategoryId = 8,
                            Description = "Magiczna opowieść o sile siostrzanej miłości.",
                            Director = "Chris Buck, Jennifer Lee",
                            Price = 19.99m,
                            Title = "Kraina Lodu"
                        },
                        new
                        {
                            FilmId = 9,
                            CategoryId = 9,
                            Description = "Dokument o systemowym rasizmie w USA.",
                            Director = "Ava DuVernay",
                            Price = 14.99m,
                            Title = "13th"
                        },
                        new
                        {
                            FilmId = 10,
                            CategoryId = 10,
                            Description = "Muzyczna opowieść o miłości i marzeniach.",
                            Director = "Damien Chazelle",
                            Price = 29.99m,
                            Title = "La La Land"
                        },
                        new
                        {
                            FilmId = 11,
                            CategoryId = 1,
                            Description = "Zemsta na najwyższym poziomie.",
                            Director = "Chad Stahelski",
                            Price = 27.99m,
                            Title = "John Wick"
                        },
                        new
                        {
                            FilmId = 12,
                            CategoryId = 2,
                            Description = "Zwariowana komedia o nieprzewidywalnej imprezie.",
                            Director = "Todd Phillips",
                            Price = 21.99m,
                            Title = "Kac Vegas"
                        },
                        new
                        {
                            FilmId = 13,
                            CategoryId = 3,
                            Description = "Epicka historia honoru i zemsty.",
                            Director = "Ridley Scott",
                            Price = 31.99m,
                            Title = "Gladiator"
                        },
                        new
                        {
                            FilmId = 14,
                            CategoryId = 4,
                            Description = "Paranormalne śledztwo na farmie.",
                            Director = "James Wan",
                            Price = 18.99m,
                            Title = "Obecność"
                        },
                        new
                        {
                            FilmId = 15,
                            CategoryId = 5,
                            Description = "Kultowy cyberpunkowy świat.",
                            Director = "Denis Villeneuve",
                            Price = 32.99m,
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            FilmId = 16,
                            CategoryId = 6,
                            Description = "Początek przygód młodego czarodzieja.",
                            Director = "Chris Columbus",
                            Price = 24.99m,
                            Title = "Harry Potter i Kamień Filozoficzny"
                        },
                        new
                        {
                            FilmId = 17,
                            CategoryId = 7,
                            Description = "Psychopatyczny morderca i jego makabryczna gra.",
                            Director = "David Fincher",
                            Price = 28.99m,
                            Title = "Siedem"
                        },
                        new
                        {
                            FilmId = 18,
                            CategoryId = 8,
                            Description = "Przygody zabawek, które żyją własnym życiem.",
                            Director = "John Lasseter",
                            Price = 20.99m,
                            Title = "Toy Story"
                        },
                        new
                        {
                            FilmId = 19,
                            CategoryId = 9,
                            Description = "Dokument o pierwszym lądowaniu na Księżycu.",
                            Director = "Todd Douglas Miller",
                            Price = 17.99m,
                            Title = "Człowiek na Księżycu"
                        },
                        new
                        {
                            FilmId = 20,
                            CategoryId = 10,
                            Description = "Musical pełen hitów ABBY.",
                            Director = "Phyllida Lloyd",
                            Price = 23.99m,
                            Title = "Mamma Mia!"
                        });
                });

            modelBuilder.Entity("film_app_magisterka.Models.Film", b =>
                {
                    b.HasOne("film_app_magisterka.Models.Category", "Category")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("film_app_magisterka.Models.Category", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
